
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.15.0
 * Query Engine version: 85179d7826409ee107a6ba334b5e305ae3fba9fb
 */
Prisma.prismaVersion = {
  client: "6.15.0",
  engine: "85179d7826409ee107a6ba334b5e305ae3fba9fb"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  money: 'money',
  bank: 'bank',
  xp: 'xp',
  companyId: 'companyId',
  mailsTagsIgnored: 'mailsTagsIgnored',
  dmNotification: 'dmNotification',
  token: 'token',
  afkReasson: 'afkReasson',
  afkTime: 'afkTime'
};

exports.Prisma.TryviaQuestionsScalarFieldEnum = {
  id: 'id',
  question: 'question',
  difficulty: 'difficulty',
  type: 'type',
  correct: 'correct',
  tags: 'tags',
  correctAnswer: 'correctAnswer',
  correctAnswersVariation: 'correctAnswersVariation',
  explanation: 'explanation',
  incorrectAnswers: 'incorrectAnswers',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  status: 'status',
  origin: 'origin'
};

exports.Prisma.ApplicationScalarFieldEnum = {
  id: 'id',
  money: 'money',
  token: 'token',
  ownerId: 'ownerId'
};

exports.Prisma.RequisitionScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  url: 'url',
  applicationId: 'applicationId'
};

exports.Prisma.LogScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  message: 'message',
  timestamp: 'timestamp',
  level: 'level',
  type: 'type',
  tags: 'tags'
};

exports.Prisma.TransactionScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  targetId: 'targetId',
  amount: 'amount',
  quitType: 'quitType',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  guildId: 'guildId',
  channelId: 'channelId',
  messageId: 'messageId',
  reason: 'reason',
  type: 'type',
  status: 'status'
};

exports.Prisma.CooldownScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  name: 'name',
  timestamp: 'timestamp',
  willEndIn: 'willEndIn'
};

exports.Prisma.CompanyScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  difficulty: 'difficulty',
  experience: 'experience',
  wage: 'wage',
  expectations: 'expectations'
};

exports.Prisma.StockScalarFieldEnum = {
  id: 'id',
  name: 'name',
  price: 'price',
  description: 'description',
  iaAvaliation: 'iaAvaliation',
  trend: 'trend'
};

exports.Prisma.StockHistoryScalarFieldEnum = {
  id: 'id',
  stockId: 'stockId',
  price: 'price',
  date: 'date'
};

exports.Prisma.StockHoldingScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  stockId: 'stockId',
  amount: 'amount'
};

exports.Prisma.GuildSettingsScalarFieldEnum = {
  id: 'id',
  chatBotChannels: 'chatBotChannels',
  chatBotEnabled: 'chatBotEnabled',
  channelsCommandDisabled: 'channelsCommandDisabled',
  channelsCommandDisabledIsHabilited: 'channelsCommandDisabledIsHabilited',
  channelsCommandEnabled: 'channelsCommandEnabled',
  channelsCommandEnabledIsHabilited: 'channelsCommandEnabledIsHabilited',
  xpSystemEnabled: 'xpSystemEnabled',
  difficulty: 'difficulty',
  rolesXpBonus: 'rolesXpBonus',
  rolesNotWinXp: 'rolesNotWinXp',
  channelsXpBonus: 'channelsXpBonus',
  channelsNotWinXp: 'channelsNotWinXp',
  warnLevelUp: 'warnLevelUp',
  levelGrant: 'levelGrant'
};

exports.Prisma.GuildMemberScalarFieldEnum = {
  id: 'id',
  guildId: 'guildId',
  xp: 'xp',
  tryviaPoints: 'tryviaPoints',
  tryviaGames: 'tryviaGames',
  tryviaWins: 'tryviaWins'
};

exports.Prisma.MailsScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  content: 'content',
  asRead: 'asRead',
  tags: 'tags',
  whoSendId: 'whoSendId',
  createdAt: 'createdAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.JsonNullValueInput = {
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};
exports.TryviaDifficulty = exports.$Enums.TryviaDifficulty = {
  EASY: 'EASY',
  MEDIUM: 'MEDIUM',
  HARD: 'HARD'
};

exports.TryviaTypes = exports.$Enums.TryviaTypes = {
  BOOLEAN: 'BOOLEAN',
  MULTIPLE: 'MULTIPLE',
  WRITEINCHAT: 'WRITEINCHAT'
};

exports.TryviaStatus = exports.$Enums.TryviaStatus = {
  APPROVED: 'APPROVED',
  PENDING: 'PENDING',
  REJECTED: 'REJECTED'
};

exports.TryviaOrigin = exports.$Enums.TryviaOrigin = {
  USER: 'USER',
  API: 'API',
  IA: 'IA',
  ADMIN: 'ADMIN'
};

exports.TransactionQuitType = exports.$Enums.TransactionQuitType = {
  SUB: 'SUB',
  SUM: 'SUM'
};

exports.TransactionType = exports.$Enums.TransactionType = {
  API: 'API',
  USER: 'USER',
  ADMIN: 'ADMIN',
  BUY: 'BUY',
  SELL: 'SELL'
};

exports.TransactionStatus = exports.$Enums.TransactionStatus = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  EXPIRED: 'EXPIRED'
};

exports.Prisma.ModelName = {
  User: 'User',
  TryviaQuestions: 'TryviaQuestions',
  Application: 'Application',
  Requisition: 'Requisition',
  Log: 'Log',
  Transaction: 'Transaction',
  Cooldown: 'Cooldown',
  Company: 'Company',
  Stock: 'Stock',
  StockHistory: 'StockHistory',
  StockHolding: 'StockHolding',
  GuildSettings: 'GuildSettings',
  GuildMember: 'GuildMember',
  Mails: 'Mails'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
